プレイヤーの攻撃時の当たり判定の作成
tricore-as17/3DActionGame pull request #13
Opened 2024-08-01 06:10 UTC by tricore-as17

・CollisionManagerの処理を追加
　・カプセル同士の当たり判定の追加
　・球とカプセルの当たり判定の追加
　
・Playerの攻撃時に当たり判定を作成

・CollisionManagerの綴りが間違っていたので名前を修正しました。
　名前を変更したので新しいファイル扱いになってしまっています。申し訳ございません。
　

2024-08-01 07:01 UTC, tricore-as03 commented on GameProject/GameProject/CollisionManager.h
> +    static VECTOR AdjustGroundToWardVelocity(VECTOR velocity, VECTOR beforePosition);
[MUST]
そのクラス内でしか呼ばない関数はprivateにしてください。

2024-08-01 07:14 UTC, tricore-as03 commented on GameProject/GameProject/Player.h
> +    int registerTag;               //レジスタの識別番号
[Q]
当たり判定が可能なオブジェクトを識別するタグだと思うのですが、CollisionDataクラスにまとめられないでしょうか？
また、`registerTag`ではなんのタグなのか分からないです。
`collidableObjectTag`とかで良いかと。（Collidable→衝突可能な）

2024-08-02 00:31 UTC, tricore-as17 commented on GameProject/GameProject/Boss.cpp
> +    collisionManager->SetResister(collisionData, registerTag);
collisionDataをポインタとして渡すように修正して、SendRegisterを削除しました。

2024-08-02 00:31 UTC, tricore-as17 commented on GameProject/GameProject/Boss.cpp
> +void Boss::ConvertCollisionData()
Convertの使い方の認識を間違えていました！UpdateCollisionDataに修正しました。

2024-08-02 00:31 UTC, tricore-as17 commented on GameProject/GameProject/CollisionManager.cpp
> +void CollisionManager::DeleteResister(int& registerTag)
個人的に分かりやすいと思ったDeleteHitObjectに変更しました！

2024-08-02 00:31 UTC, tricore-as17 commented on GameProject/GameProject/CollisionManager.h
> +    static VECTOR AdjustGroundToWardVelocity(VECTOR velocity, VECTOR beforePosition);
申し訳ございません。privateに移行させました。

2024-08-02 00:32 UTC, tricore-as17 commented on GameProject/GameProject/Player.h
> +    int registerTag;               //レジスタの識別番号
CollisionDataにまとめて、変数名もcollidableObjectTagに変更しました。

2024-08-02 01:02 UTC, tricore-as03 requested changes

2024-08-02 01:02 UTC, tricore-as03 commented on GameProject/GameProject/CollisionManager.h
> +    static constexpr int   NotRegisterTag = -1;   //レジスタの識別番号が代入されていないことをしめす
[MUST]
enumの`HitObjectTag`にNoneを追加する形でよいかと。

2024-08-02 03:25 UTC, tricore-as17 commented on GameProject/GameProject/CollisionManager.h
> +    static constexpr int   NotRegisterTag = -1;   //レジスタの識別番号が代入されていないことをしめす
CollidableObjectTagを削除する形で実装したので、定数も削除しました。

2024-08-02 03:25 UTC, tricore-as17 commented on GameProject/GameProject/Boss.cpp
> +    }
申し訳ございません。OnHit自体は残しておいて処理なしコメントを追加しました。

2024-08-02 03:37 UTC, tricore-as03 requested changes

2024-08-02 03:37 UTC, tricore-as03 commented on GameProject/GameProject/CollisionManager.cpp
> -void CollisionManager::DeleteHitObject(int& collidableObjectTag)
[Q]
Delete関数も消しているようですが、ゲーム終了時のhitObjectListの解放はできていますか？

2024-08-02 04:01 UTC, tricore-as17 commented on GameProject/GameProject/CollisionManager.cpp
> -void CollisionManager::DeleteHitObject(int& collidableObjectTag)
hitObjectListの中身は動的に確保していないので、Playerなどの各クラスが削除された際に自動的に解放されると思います。元々、Delete関数自体の処理はUpdateの中で行うようにしました。

2024-08-02 04:50 UTC, tricore-as03 commented on GameProject/GameProject/CollisionManager.cpp
> -void CollisionManager::DeleteHitObject(int& collidableObjectTag)
了解です。承認しました。

2024-08-02 04:50 UTC, tricore-as03 approved these changes
LGTM

2024-08-02 05:32 UTC, merged