ボスの通常攻撃の当たり判定を追加
tricore-as17/3DActionGame pull request #15
Opened 2024-08-05 02:32 UTC by tricore-as17

追加したもの
・当たり判定を作成するステートで同じような関数があったので基底クラスのCollisionStateBaseを追加しました。
・CollisionStateBaseには当たり判定用のカプセルの移動や回転用の関数を用意したり、CollisionManagerのインスタンスにアクセスできるポインタの準備などの処理を行わせています。

修正した箇所
・CollisionStateBaseの追加にともなってPlayerAttackStateも関数の追加などの変更を行いました。

2024-08-06 07:32 UTC, tricore-as03 requested changes

2024-08-06 07:32 UTC, tricore-as03 commented on GameProject/GameProject/CollisionStateBase.h
[Q]
処理の共通化にも様々な方法がある中で、基底クラスを用意する方法にしたのはどういった意図がありますでしょうか？

2024-08-06 07:54 UTC, tricore-as17 commented on GameProject/GameProject/CollisionStateBase.h
CollisionStateの参照を持たせるという方法も考えたのですが、基底クラスとして用意したほうがSetterなどを使わず値を書き換えれるのと絶対に必要な関数をabstract化することで、関数の定義漏れなどが無くなると思ったので、基底クラスにする形にしました。

2024-08-06 09:46 UTC, tricore-as03 requested changes

2024-08-06 09:46 UTC, tricore-as03 commented on GameProject/GameProject/CollisionStateBase.h
単純にCollisionUtilityのようなstaticな汎用関数をまとめたクラスでよいと思うのですがどうでしょうか？
CollisionStateBaseをみるに、引数で値を受け取って更新を行っているような関数ばかりなので、結果を戻り値で受け取って、更新自体は呼び出し元のUpdate関数で行えば、わざわざ別クラスで変数を保持して状態を把握する必要もないかと。
また、abstractで実装を強制させている割にはCollisionStateBaseを継承しているステートとそうでないステートが混在していて、共通化が中途半端になってしまってます。

2024-08-08 02:34 UTC, tricore-as17 commented on GameProject/GameProject/CollisionStateBase.h
承知いたしました。CollisionStateBaseを削除してCollisionUtilityに関数の処理だけ移しました！

2024-08-08 02:39 UTC, tricore-as03 approved these changes
LGTM

2024-08-08 02:41 UTC, merged