プレイヤーと地面の当たり判定の追加
tricore-as17/3DActionGame pull request #7
Opened 2024-07-23 08:34 UTC by tricore-as17

Y座標が0より低くならないような処理を追加しました。

2024-07-23 09:36 UTC, tricore-as07 requested changes

2024-07-23 09:36 UTC, tricore-as07 commented on GameProject/GameProject/GameScene.cpp
> +    //メモリの解放
[Q]
Playerのメモリ解放を行っていない理由って何かありますか？

2024-07-23 09:36 UTC, tricore-as07 commented on GameProject/GameProject/Stage.cpp
> +    modelDataManager = ModelDataManager::GetInstance();
[MUST]
ModelDataManagerにコンストラクタ以外でアクセスしないのであれば、
メンバ変数としてインスタンスを保持しなくても問題ないと思います

2024-07-25 02:35 UTC, tricore-as17 commented on GameProject/GameProject/GameScene.cpp
> +    //メモリの解放
ただのメモリ解放忘れです！申し訳ございません。

2024-07-25 02:35 UTC, tricore-as17 commented on GameProject/GameProject/Stage.cpp
> +    modelDataManager = ModelDataManager::GetInstance();
確かにその通りでした！ローカル変数に変更しました。

2024-07-25 02:41 UTC, tricore-as07 approved these changes
LGTM

2024-07-25 02:49 UTC, merged