プレイヤーの移動と静止状態のステートを作成しました。
tricore-as17/3DActionGame pull request #9
Opened 2024-07-25 03:14 UTC by tricore-as17

Scene遷移と同じような形でStateの移行も行うようにしました。

2024-07-25 05:21 UTC, tricore-as03 requested changes

2024-07-25 05:21 UTC, tricore-as03 commented on GameProject/GameProject/InputManager.cpp
> +            reverseKeyTag.at(input);
[MUST]
try-catchはあくまで例外を処理するために使うものなので、それ以外で使用するのはよくないです。
単純にキーが存在するかどうか判定するだけであれば、[contains](https://cpprefjp.github.io/reference/map/map/contains.html)で良いかと。

2024-07-26 00:57 UTC, tricore-as17 commented on GameProject/GameProject/InputManager.cpp
> +            reverseKeyTag.at(input);
すみません。あまり理解できていない状態で使用していました。
これ以降のプルリクでInputManagerの変更をしていて、try-catchを使用しなくなっているので現在のプルリクではそのままにしていても良いでしょうか？

2024-07-26 00:57 UTC, tricore-as17 commented on GameProject/GameProject/InputManager.h
> +        Other      = 18,  //使用しないキーもしくは押されていない
Noneに変更しました！

2024-07-26 01:27 UTC, tricore-as03 commented on GameProject/GameProject/InputManager.cpp
> +            reverseKeyTag.at(input);
了解です。

2024-07-26 01:28 UTC, tricore-as03 approved these changes
LGTM

2024-07-26 01:29 UTC, merged